"""Domain models, identities, states, errors, and scoring logic for job_finder."""
from __future__ import annotations

from .candidate import (
    CandidateFact,
    CandidateProfile,
    CandidateProfileVersion,
    ClaimType,
    FactProvenance,
    SourceKind,
    SourceReference,
)
from .errors import (
    CandidateValidationError,
    DomainError,
    InvalidStateTagError,
    InvalidTimezoneError,
    JobIdentityValidationError,
    ScoringPolicyValidationError,
    ScoringValidationError,
)
from .ids import (
    CandidateFactId,
    CandidateId,
    CandidateProfileId,
    CandidateProfileVersionId,
    CandidateSourceId,
    JobId,
    UserTimezone,
)
from .job_identity import (
    IDENTITY_UNVERIFIED_AUDIT_STATUS,
    CanonicalCompanyKey,
    CanonicalJobIdentity,
    ExternalJobId,
    IdentityUnverified,
    IdentityUnverifiedReason,
    JobIdentityHash,
    JobSource,
    build_job_identity,
)
from .scoring import (
    CriterionEvaluation,
    CriterionEvidenceStatus,
    CriterionScoreExplanation,
    FactorScoreExplanation,
    ScoreResult,
    score_criteria,
)
from .scoring_policy import (
    CURRENT_SCORING_POLICY,
    CURRENT_SCORING_POLICY_VERSION,
    ScoringFactor,
    ScoringPolicy,
    ScoringPolicyVersion,
)
from .states import (
    CheckpointState,
    EligibilityDecision,
    WorkflowState,
    parse_checkpoint_state,
    parse_eligibility_decision,
    parse_workflow_state,
)

__all__ = [
    "CURRENT_SCORING_POLICY",
    "CURRENT_SCORING_POLICY_VERSION",
    "IDENTITY_UNVERIFIED_AUDIT_STATUS",
    "CandidateFact",
    "CandidateFactId",
    "CandidateId",
    "CandidateProfile",
    "CandidateProfileId",
    "CandidateProfileVersion",
    "CandidateProfileVersionId",
    "CandidateSourceId",
    "CandidateValidationError",
    "CanonicalCompanyKey",
    "CanonicalJobIdentity",
    "CheckpointState",
    "ClaimType",
    "CriterionEvaluation",
    "CriterionEvidenceStatus",
    "CriterionScoreExplanation",
    "DomainError",
    "EligibilityDecision",
    "ExternalJobId",
    "FactProvenance",
    "FactorScoreExplanation",
    "IdentityUnverified",
    "IdentityUnverifiedReason",
    "InvalidStateTagError",
    "InvalidTimezoneError",
    "JobId",
    "JobIdentityHash",
    "JobIdentityValidationError",
    "JobSource",
    "ScoreResult",
    "ScoringFactor",
    "ScoringPolicy",
    "ScoringPolicyValidationError",
    "ScoringPolicyVersion",
    "ScoringValidationError",
    "SourceKind",
    "SourceReference",
    "UserTimezone",
    "WorkflowState",
    "build_job_identity",
    "parse_checkpoint_state",
    "parse_eligibility_decision",
    "parse_workflow_state",
    "score_criteria",
]
